### ISSUE TITLE
Review 'ethnicity' variable/values

### ISSUE THREAD

**Issue by mrueschman** [nsrr/cfs-data-dictionary#244]
https://sleepdata.org/datasets/cfs/variables/ethnicity

Right now we have 3 subjects as "Hispanic or Latino" and everyone else is missing. It seems unlikely that this question was missed on so many at Visit 5. Running a frequency on SAS on the `combined` dataset seems to indicate all the currently missing should actually be "Not Hispanic of Latino".

**Comment by mcailler** [comment]
I imagine this is going to become a larger investigation, given Jia's findings on hispanic vs ethnicity?

**Comment by mrueschman** [comment]
I suspect so.

**Comment by mrueschman** [comment]
Closed. 'ethnicity' variable confirmed otherwise.
